parameters:
    oauth_private_key: 'file://%kernel.project_dir%/config/jwt/private.key'
    oauth_public_key: 'file://%kernel.project_dir%/config/jwt/public.key'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    League\OAuth2\Server\AuthorizationServer:
        factory: ['@App\OAuth\AuthorizationServerFactory', 'create']

    App\OAuth\AuthorizationServerFactory:
        arguments:
            $privateKey: '%oauth_private_key%'
            $encryptionKey: '%env(OAUTH_ENCRYPTION_KEY)%'

    League\OAuth2\Server\ResourceServer:
        arguments:
            $accessTokenRepository: '@App\Repository\AccessTokenRepository'
            $publicKey: '%oauth_public_key%'

    App\EventListener\RequestLoggerListener:
        arguments:
            $logger: '@monolog.logger.requests'
