# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    League\OAuth2\Server\AuthorizationServer:
        arguments:
            $clientRepository: '@App\Repository\ClientRepository'
            $accessTokenRepository: '@App\Repository\AccessTokenRepository'
            $scopeRepository: '@App\Repository\ScopeRepository'
            $privateKey: '%kernel.project_dir%/var/oauth/private.key'
            $encryptionKey: '%env(OAUTH2_ENCRYPTION_KEY)%'
        calls:
            - enableGrantType:
                  - !service
                      class: League\OAuth2\Server\Grant\ClientCredentialsGrant
                  - !service
                      class: DateInterval
                      arguments: ['PT1H']
